[package]
name = "navi_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.100"
tokio = { version = "1.47.1", features = ["sync", "macros", "rt-multi-thread"] }
rclrs = { path = "../../../../rs_dep/install/rclrs/share/rclrs/rust" }
rosidl_runtime_rs = { path = "../../../../rs_dep/install/rosidl_runtime_rs/share/rosidl_runtime_rs/rust" }
builtin_interfaces = { path = "../../../../rs_dep/install/builtin_interfaces/share/builtin_interfaces/rust" }
std_msgs = { path = "../../../../rs_dep/install/std_msgs/share/std_msgs/rust" }
geometry_msgs = { path = "../../../../rs_dep/install/geometry_msgs/share/geometry_msgs/rust" }
ros2_tools = { path = "../../../../rs_ws/install/ros2_tools/share/ros2_tools/rust" }

[dev-dependencies]
tokio-test = "0.4"

[[bin]]
name = "navi_rs"
path = "src/main.rs"
