controller_manager:
  ros__parameters:
    update_rate: 100

mecanum_controller:
  ros__parameters:
    type: "mecanum_drive_controller/MecanumDriveController"
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    front_left_wheel_state_joint_name: "front_left_wheel_joint"
    front_right_wheel_state_joint_name: "front_right_wheel_joint"
    rear_left_wheel_state_joint_name: "rear_left_wheel_joint"
    rear_right_wheel_state_joint_name: "rear_right_wheel_joint"
    kinematics:
      wheels_radius: 0.05
      sum_of_robot_center_projection_on_X_Y_axis: 0.45
    use_stamped_vel: true
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
