<robot name="my_base" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="my_base">
    <!-- 宏:颜色设置 -->
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>
    <material name="yellow">
        <color rgba="1.0 1.0 0.0 1.0" />
    </material>

    <!-- 底盘主体 -->
    <link name="base_link">
      <visual>
        <geometry>
          <cylinder radius="${base_link_radius}" length="${base_link_length}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <material name="yellow">
          <color rgba="0.5 0.3 0.0 0.5" />
        </material>
      </visual>
    </link>

    <!-- 四个驱动轮宏 -->
    <xacro:macro name="add_wheel" params="name x y">
      <link name="${name}_wheel">
        <visual>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}" />
          </geometry>
          <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
          <material name="yellow"/>
        </visual>
        <collision>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}" />
          </geometry>
          <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
          <!-- 添加摩擦力 -->
          <surface>
            <friction>
              <ode>
                <mu>0.2</mu>      <!-- 主摩擦系数 -->
                <mu2>0.2</mu2>    <!-- 次摩擦系数 -->
              </ode>
            </friction>
          </surface>
        </collision>
        <xacro:cylinder_inertial_matrix m="${wheel_m}" r="${wheel_radius}" h="${wheel_length}"/>
      </link>

      <joint name="${name}_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="${name}_wheel"/>
        <origin xyz="${x} ${y} ${-(earth_space + base_link_length/2 - wheel_radius)}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
      </joint>
      <gazebo reference="${name}_wheel">
        <material>Gazebo/yellow</material>
      </gazebo>
    </xacro:macro>

    <!-- 四个角生成麦轮 -->
    <xacro:add_wheel name="front_left"  x="${ wheel_x_offset}"  y="${ wheel_y_offset}"/>
    <xacro:add_wheel name="front_right" x="${ wheel_x_offset}"  y="-${ wheel_y_offset}"/>
    <xacro:add_wheel name="rear_left"   x="-${wheel_x_offset}" y="${ wheel_y_offset}"/>
    <xacro:add_wheel name="rear_right"  x="-${wheel_x_offset}" y="-${wheel_y_offset}"/>
  </xacro:macro>
</robot>